// let newBtn = document.createElement("button");
// newBtn.innerText = "Click me!";

// newBtn.style.color = "white";
// newBtn.style.backgroundColor = "red";

// document.querySelector("body").prepend(newBtn);


let para = document.querySelector("p");
para.getAttribute("class");
// para.setAttribute("class","newClass");

para.classList.add("newClass");
para.classList.remove("newClass");

